speed_sector_tuner:
  ros__parameters:
    save_params: false
    phase_multiplier: 1.0
    n_sectors: 3
    Sector0:
      start: 0
      end: 12
      scaling: 0.5
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 13
      end: 127
      scaling: 0.5
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 128
      end: 406
      scaling: 0.5
      only_FTG: false
      no_FTG: false
