speed_sector_tuner:
  ros__parameters:
    save_params: false
    global_limit: 1.0
    n_sectors: 4
    Sector0:
      start: 0
      end: 71
      scaling: 0.8
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 72
      end: 113
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 114
      end: 186
      scaling: 0.8
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 187
      end: 229
      scaling: 0.6
      only_FTG: false
      no_FTG: false
