speed_sector_tuner:
  ros__parameters:
    save_params: false
    phase_multiplier: 1.0
    n_sectors: 5
    Sector0:
      start: 0
      end: 67
      scaling: 1.3
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 68
      end: 127
      scaling: 1.15
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 128
      end: 251
      scaling: 1.2
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 252
      end: 330
      scaling: 1.1
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 331
      end: 397
      scaling: 1.3
      only_FTG: false
      no_FTG: false
