speed_sector_tuner:
  ros__parameters:
    save_params: false
    phase_multiplier: 1.0
    n_sectors: 6
    Sector0: # 코너 (헤어핀 in)
      start: 0
      end: 29
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector1: # 코너 (헤어핀 out)
      start: 30
      end: 80
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector2: # 꼬불 직선
      start: 81
      end: 164
      scaling: 1.25
      only_FTG: false
      no_FTG: false
    Sector3: # 코너 (M in)
      start: 165
      end: 203
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector4: # 코너 (M out)
      start: 204
      end: 245
      scaling: 1.05
      only_FTG: false
      no_FTG: false
    Sector5: # 직선
      start: 246
      end: 369
      scaling: 1.5
      only_FTG: false
      no_FTG: false
